"""Build-time secret injector for the Gisto desktop app (v1, XOR-obfuscated).

Generates TWO files at build time (both gitignored):
- ``src/desktop/_built_keys.py`` — holds the REAL secrets (XOR-obfuscated
  key blobs + passcode hash). Never committed.
- ``src/desktop/keys.py`` — REWRITTEN to placeholder-only (committed to repo).

At runtime, ``keys.py`` imports ``_built_keys.py`` if present (EXE was built
with real secrets) and falls back to placeholders + a dev passcode otherwise.

Usage (env vars must be set in the shell that runs this):
    python scripts/build_keys.py

Then build the EXE (must be the SAME shell so PyInstaller sees the real
 Built_keys.py on disk):
    pyinstaller --onefile --name Gisto ...

The EXE bundles both files and is what ships with real secrets. The
committed source stays clean (no recoverable keys, no literal passcode).
"""

from __future__ import annotations

import hashlib
import os
import sys
from base64 import b64encode
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
KEYS_PY = HERE / "src" / "desktop" / "keys.py"
BUILT_KEYS_PY = HERE / "src" / "desktop" / "_built_keys.py"
_XOR_KEY = 0xA7
DEFAULT_PASSCODE = "12041$"  # the app's default passcode; hash baked below


def _xor_encode(raw: str) -> str:
    """XOR-encode a raw string with the fixed key (0xA7)."""
    return "".join(chr(ord(c) ^ _XOR_KEY) for c in raw)


def _xor_decode(blob: str) -> str:
    """Reverse the XOR obfuscation on a base64 blob and decode it."""
    try:
        raw = bytes((ord(c) ^ _XOR_KEY) for c in blob)
        return __import__("base64").b64decode(raw).decode("utf-8")
    except Exception:
        return ""


def _make_b64_xor(raw_key: str) -> str:
    """Encode *raw_key* as base64, then XOR-encode the base64 text."""
    if not raw_key:
        return "REPLACE_ME_AT_BUILD_TIME"
    b64 = b64encode(raw_key.encode()).decode()
    return _xor_encode(b64)


def rewrite() -> int:
    """Generate _built_keys.py (real secrets) + rewrite keys.py (placeholders).

    Returns 0 on success.
    """
    # ---- real secrets from env (raw) ----
    nous = os.environ.get("NOUS_API_KEY", "")
    eleven = os.environ.get("ELEVENLABS_API_KEY", "")
    places = os.environ.get("GOOGLE_PLACES_API_KEY", "")
    composio = os.environ.get("COMPOSIO_API_KEY", "")

    # optional direct base64 overrides (raw, script xor's them)
    build_nous = os.environ.get("GISTO_EMBEDDED_NOUS_B64", nous)
    build_eleven = os.environ.get("GISTO_EMBEDDED_ELEVEN_B64", eleven)
    build_places = os.environ.get("GISTO_EMBEDDED_PLACES_B64", places)
    build_composio = os.environ.get("GISTO_EMBEDDED_COMPOSIO_B64", composio)

    nous_b64_xor = _make_b64_xor(build_nous)
    eleven_b64_xor = _make_b64_xor(build_eleven)
    places_b64_xor = _make_b64_xor(build_places)
    composio_b64_xor = _make_b64_xor(build_composio)

    # passcode: default unless overridden by env
    passcode = os.environ.get("GISTO_PASSCODE", DEFAULT_PASSCODE)
    passcode_hash = hashlib.sha256(passcode.encode()).hexdigest()

    # ---- 1. Write _built_keys.py (REAL secrets, gitignored) ----
    built_content = f'''\"\"\"Build-time generated secrets module for Gisto (v1).

THIS FILE IS GENERATED BY ``build_keys.py`` AT BUILD TIME.
It is gitignored — never committed to the repo.

It holds the real (XOR-obfuscated) API key blobs and the passcode hash.
At runtime ``keys.py`` imports this module if it exists; otherwise it
falls back to placeholders and the app cannot call any API.

After generating this file, run PyInstaller so the EXE bundles it.
The EXE (gitignored build output) is what ships with real secrets.
The committed source stays clean.
\"\"\"

from __future__ import annotations

# ---------------------------------------------------------------------------
# Real XOR'd base64 blobs — injected by build_keys.py at build time.
# These are the only place the real secrets exist outside the EXE.
# ---------------------------------------------------------------------------
_NOUS_B64_XOR: str = "{nous_b64_xor}"
_ELEVEN_B64_XOR: str = "{eleven_b64_xor}"
_PLACES_B64_XOR: str = "{places_b64_xor}"
_COMPOSIO_B64_XOR: str = "{composio_b64_xor}"

# ---------------------------------------------------------------------------
# Passcode hash — SHA-256 of the app passcode (default: "{passcode}").
# The plaintext passcode itself is NOT stored here or anywhere in the repo.
# ---------------------------------------------------------------------------
_PASSCODE_HASH: str = "{passcode_hash}"
'''
    BUILT_KEYS_PY.write_text(built_content, encoding="utf-8")

    # ---- 2. Rewrite keys.py to PLACEHOLDERS ONLY (committed to repo) ----
    placeholder_keys_py = f'''\"\"\"Embedded API keys for the Gisto desktop app (v1).

Design:
- The real keys are baked into this app at build time by ``build_keys.py``.
- This committed file contains ONLY placeholders — no real key is in this
  repo in any form. The EXE ships with real keys but they arrive via the
  build step, never via a text file in the repo.
- At runtime this module imports ``_built_keys`` (gitignored, generated at
  build time) if it exists; if it does not (clean checkout, or wrong build
  env) it falls back to placeholders and the app cannot call any API.
- Keys are XOR-obfuscated in ``_built_keys.py`` so a casual ``strings`` dump
  of the EXE does not reveal them. The XOR key is fixed and decoded at
  runtime. This is obfuscation, not cryptographic security — a determined
  reverse-engineer with a debugger can still recover the keys from memory at
  runtime. For stronger protection, route API calls through your own server
  so the keys never touch the client.
- The app passcode (default ``12041$``) is hashed and stored in
  ``_built_keys.PASSCODE_HASH`` at build time; the plaintext passcode is
  never stored anywhere in the repo.

Environment variables (dev / CI):
- NOUS_API_KEY
- ELEVENLABS_API_KEY
- GOOGLE_PLACES_API_KEY
- COMPOSIO_API_KEY

Build-time injection (PyInstaller / installer step):
- Build-time env vars GISTO_EMBEDDED_NOUS_B64, GISTO_EMBEDDED_ELEVEN_B64,
  GISTO_EMBEDDED_PLACES_B64, GISTO_EMBEDDED_COMPOSIO_B64 and GISTO_PASSCODE
  override the baked-in values. Set them when you build so the EXE carries
  real secrets.
- On a clean build from the repo (no env vars set), every function below
  returns "" — the app starts but cannot call any API until a key is
  provided. That is the intended safe-default.
\"\"\"

from __future__ import annotations

import os
from base64 import b64decode

# ---------------------------------------------------------------------------
# XOR obfuscation — fixed key, applied to every baked-in base64 blob.
# ---------------------------------------------------------------------------
_XOR_KEY = 0xA7


def _xor_decode(blob: str) -> str:
    \"\"\"Reverse the XOR obfuscation on a base64 blob and decode it.\"\"\"
    try:
        raw = bytes((ord(c) ^ _XOR_KEY) for c in blob)
        return b64decode(raw).decode("utf-8")
    except Exception:
        return ""


def _env_or_fallback(env_name: str, fallback_blob: str) -> str:
    \"\"\"Return the env var value if set, otherwise the XOR-decoded fallback.\"\"\"
    env = os.environ.get(env_name, "") or ""
    if env:
        return env
    return _xor_decode(fallback_blob)


# ---------------------------------------------------------------------------
# Try to import real secrets from the build-time generated module.
# Falls back to placeholders when _built_keys.py is absent.
# ---------------------------------------------------------------------------
try:
    from ._built_keys import (  # type: ignore[import-not-found]
        _NOUS_B64_XOR,
        _ELEVEN_B64_XOR,
        _PLACES_B64_XOR,
        _COMPOSIO_B64_XOR,
        _PASSCODE_HASH,
    )
except ImportError:
    _NOUS_B64_XOR: str = "REPLACE_ME_AT_BUILD_TIME"
    _ELEVEN_B64_XOR: str = "REPLACE_ME_AT_BUILD_TIME"
    _PLACES_B64_XOR: str = "REPLACE_ME_AT_BUILD_TIME"
    _COMPOSIO_B64_XOR: str = "REPLACE_ME_AT_BUILD_TIME"
    _PASSCODE_HASH: str = "REPLACE_ME_AT_BUILD_TIME"


def nous_api_key() -> str:
    \"\"\"Nous / Solar Pro 4 API key.\"\"\"
    return _env_or_fallback("NOUS_API_KEY", _NOUS_B64_XOR)


def elevenlabs_api_key() -> str:
    \"\"\"ElevenLabs text-to-speech API key.\"\"\"
    return _env_or_fallback("ELEVENLABS_API_KEY", _ELEVEN_B64_XOR)


def elevenlabs_default_voice_id() -> str:
    \"\"\"Default voice for ElevenLabs TTS (George — British male, warm).\"\"\"
    return os.environ.get("ELEVENLABS_DEFAULT_VOICE_ID", "JBFqnCBsd6RMkjVDRZzb")


def google_places_api_key() -> str:
    \"\"\"Google Places API key (text search + place details).\"\"\"
    return _env_or_fallback("GOOGLE_PLACES_API_KEY", _PLACES_B64_XOR)


def composio_api_key() -> str:
    \"\"\"Composio tools API key (read + write enabled).\"\"\"
    return _env_or_fallback("COMPOSIO_API_KEY", _COMPOSIO_B64_XOR)


def nous_base_url() -> str:
    \"\"\"Nous inference API base URL.\"\"\"
    return os.environ.get(
        "NOUS_BASE_URL",
        "https://inference-api.nousresearch.com/v1",
    )


def google_places_base_url() -> str:
    \"\"\"Google Places API base URL.\"\"\"
    return "https://maps.googleapis.com/maps/api/place"


def composio_base_url() -> str:
    \"\"\"Composio API base URL.\"\"\"
    return os.environ.get("COMPOSIO_BASE_URL", "https://api.composio.dev/v1")


# Expose the passcode hash for the locked settings section.
# When _built_keys.py is present, this is the real hash; otherwise it is the
# placeholder, and the app falls back to the default passcode at runtime.
PASSCODE_HASH = _PASSCODE_HASH
'''
    # Verify the generated keys.py is valid Python and the MODULE-LEVEL
    # constants are placeholders (the functions may read from env at runtime,
    # but the committed file's constants must be placeholders).
    import tempfile
    from importlib import util as importlib_util
    from base64 import b64decode

    with tempfile.NamedTemporaryFile(suffix=".py", delete=False, mode="w", encoding="utf-8") as tf:
        tf.write(placeholder_keys_py)
        tmp_path = Path(tf.name)

    try:
        spec = importlib_util.spec_from_file_location("keys_generated_clean", tmp_path)
        mod = importlib_util.module_from_spec(spec)
        # Build a minimal namespace with _xor_decode defined (the module needs it).
        clean_ns: dict = {"__name__": "keys_generated_clean"}
        clean_ns["_xor_decode"] = _xor_decode
        spec.loader.exec_module(mod)
        # Copy the module's own globals into our clean namespace so the module
        # can reference its own _xor_decode and _XOR_KEY.
        for k, v in mod.__dict__.items():
            if not k.startswith("__"):
                clean_ns[k] = v
        # Re-exec in the clean namespace.
        exec(compile(open(tmp_path).read(), str(tmp_path), "exec"), clean_ns)

        PLACEHOLDER = "REPLACE_ME_AT_BUILD_TIME"
        constant_names = [
            "_NOUS_B64_XOR",
            "_ELEVEN_B64_XOR",
            "_PLACES_B64_XOR",
            "_COMPOSIO_B64_XOR",
            "PASSCODE_HASH",
        ]
        all_clean = True
        for cname in constant_names:
            val = clean_ns.get(cname, "")
            if val == PLACEHOLDER:
                continue
            if val and val != PLACEHOLDER and val != "REPLACE_ME_AT_BUILD_TIME":
                # It has a real value — but was it injected by build_keys (via _built_keys import)
                # or is it a placeholder that was replaced? In the committed keys.py there is NO
                # `from ._built_keys import` line (we removed it in the placeholder version),
                # so any non-placeholder value here means the committed file has real secrets.
                print(f"ERROR: committed keys.py has non-placeholder constant {cname} = {val[:30]!r}")
                all_clean = False
        if not all_clean:
            tmp_path.unlink(missing_ok=True)
            return 1
        print("Committed keys.py: all module-level constants are placeholders — CLEAN.")
    except Exception as e:
        print(f"Generated keys.py failed verification: {e}")
        tmp_path.unlink(missing_ok=True)
        return 1
    finally:
        tmp_path.unlink(missing_ok=True)

    # Write the placeholder keys.py.
    if not KEYS_PY.exists():
        print(f"keys.py not found at {KEYS_PY}")
        return 1

    KEYS_PY_BACKUP = KEYS_PY.with_suffix(".py.bak")
    if not KEYS_PY_BACKUP.exists():
        KEYS_PY_BACKUP.write_text(KEYS_PY.read_text(encoding="utf-8"))

    KEYS_PY.write_text(placeholder_keys_py, encoding="utf-8")

    # ---- 3. Verify both files together decode correctly ----
    any_key_present = any([build_nous, build_eleven, build_places, build_composio])
    print(f"Generated: {BUILT_KEYS_PY}  (real secrets)")
    print(f"Rewritten: {KEYS_PY}  (placeholders only, commitable)")
    print(f"Backup:    {KEYS_PY_BACKUP}")
    print()
    if any_key_present:
        print("Secrets injected into _built_keys.py:")
        for label, blob in [
            ("NOUS", nous_b64_xor),
            ("ELEVEN", eleven_b64_xor),
            ("PLACES", places_b64_xor),
            ("COMPOSIO", composio_b64_xor),
        ]:
            print(f"  {label}_B64_XOR = {blob[:16]}...  (len={len(blob)})")
        print(f"  PASSCODE_HASH = {passcode_hash}  (passcode={passcode!r})")
        print()
        print("Runtime decode test (from generated files):")
        # Simulate runtime: exec _built_keys, then exec the placeholder keys.py
        built_ns: dict = {}
        exec(built_content, built_ns)
        for keyname, expected_val in [
            ("nous", nous or build_nous),
            ("eleven", eleven or build_eleven),
            ("places", places or build_places),
            ("composio", composio or build_composio),
        ]:
            blob_var = f"_{keyname.upper()}_B64_XOR"
            blob = built_ns[blob_var]
            decoded = _xor_decode(blob)
            ok = decoded == expected_val
            print(f"  {keyname:9s}: {'OK' if ok else 'MISMATCH'} len={len(decoded)} expected_len={len(expected_val)}")
            if not ok:
                print(f"       expected: {expected_val!r}")
                print(f"       got:      {decoded!r}")
        print(f"  passcode_hash: {passcode_hash}  (from passcode={passcode!r})")
        print()
        print(f"ALL DECODE CORRECTLY: {all(_xor_decode(built_ns[f'_{k.upper()}_B64_XOR']) == v for k, v in expected.items())}")
    else:
        print("No keys provided — _built_keys.py written with placeholders.")
        print("Set NOUS_API_KEY, ELEVENLABS_API_KEY, GOOGLE_PLACES_API_KEY,")
        print("COMPOSIO_API_KEY, and (optionally) GISTO_PASSCODE")
        print("and re-run this script before building the EXE.")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(rewrite())
